### ISSUE TITLE
Other os

### ISSUE THREAD

**Issue by imSunnyk** [Raviteja-Ainampudi/Dynamic-Encryption-And-Decryption-of-Any-files#1]
Can this project be executed on windows?

**Comment by Raviteja-Ainampudi** [comment]
Yes, It can be deployed/executed on windows as well.

If you have docker available on your PC. You can run it. Then you can encrypt and decrypt files inside the container. 

If not, you can deploy the Flask API in app.py and use it from that current folder. 

If suggest you to AVOID running this project system files directory or drive. Because if you forget the password. You cannot decrypt them. 

If you want contribute to this project. Feel free to do so.

**Comment by imSunnyk** [comment]
> Yes, It can be deployed/executed on windows as well.
> 
> If you have docker available on your PC. You can run it. Then you can encrypt and decrypt files inside the container. 
> 
> If not, you can deploy the Flask API in app.py and use it from that current folder. 
> 
> If suggest you to AVOID running this project system files directory or drive. Because if you forget the password. You cannot decrypt them. 
> 
> If you want contribute to this project. Feel free to do so. 

Thank you
